---
version: 2.1

orbs:
  python: circleci/python@2.0

jobs:
  test-python:
    docker:
      - image: cimg/python:3.10-node
    working_directory: ~/project/bankchurn-api
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: tox
      - store_test_results:
          path: junit.xml

  deploy_app_to_railway:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy to Railway
          command: railway up --service=splendid-upliftment

workflows:
  build-and-deploy:
    jobs:
      - test-python
      - deploy_app_to_railway:
          requires:
            - test-python
